owner: http403
repo: uptime_monitor

sites:
  - name: Wenku8
    url: https://www.wenku8.net
  - name: Masiro Me
    url: https://masiro.me/admin/auth/login

assignees:
  - http403

status-website:
  cname: up.sparvojo.pw
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Are these websites up?
  navbar:
    - title: Status
      href: /
